### ISSUE TITLE
When running Chrome 57.0.2987.98  under awesome, clicks don't always work

### ISSUE THREAD

**Issue by chadcatlett** [awesomeWM/awesome#1658]
Output of `awesome --version`:

```
$ awesome --version
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```
**How to reproduce the issue:**

1. Browse to http://memset.com/
2. Hover over Services
3. Move mouse to Virtual Servers under the Servers heading on the left
4. Click Virtual Servers link

**Actual result:**

Click doesn't seem to have made it to the browser.

**Expected result:**

Click should have made it to the browser and the browser loads Virtual Servers link.

**Notes:**

It's worth noting in a previous version of Chrome this did not occur. Also worth noting that switching to XFCE4, Openbox, i3, etc. and Chrome works correctly.

I'm not stating the issue is actually awesome, but it's strange that works fine under other WMs but not awesome. 

I opened an issue with the Chromium project, it is located at https://bugs.chromium.org/p/chromium/issues/detail?id=702255 . I'll update the Chromium issue with this issue as well.

**Comment by 0x041E** [comment]
Found what causes the issue it is in awesome. In rc.lua clientbuttons bind for left mouse
`awful.button({ }, 1, function (c) client.focus = c; c:raise() end),`
If you comment out this line and reload config then clicking on that site works correctly although mouse focus for windows is obviously partially broken since you unbound window focus so you have to use keyboard binds to focus windows.

**Comment by psychon** [comment]
Same issue as #1479

**Comment by psychon** [comment]
Fixed in Chromium according to https://github.com/awesomeWM/awesome/issues/1479#issuecomment-287410587, could someone test?

**Comment by Philosoft** [comment]
dunno how to verify if this commit belongs to a specific buuild. tried [latest beta](https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F464322%2Fchrome-linux.zip?alt=media) - still the same

**Comment by AranelSurion** [comment]
It seems this bug is fixed in the latest unstable Chrome version, at least it worked fine on my awesome3.5 debian setup.

See: https://www.google.com/chrome/browser/desktop/index.html?platform=linux&extra=devchannel

**Comment by psychon** [comment]
Could someone test if #1724 really fixes this issue?

**Comment by cars10** [comment]
Nothing is fixed. I am using Chromium Version 59.0.3071.115 and awesome 4.1 and still experience the same issue.

**Comment by ewnd9** [comment]
@cars10 Fix was released after 4.1, you need to build from master.

**Comment by cars10** [comment]
I just build from master with `awesome-luajit-git` package on arch and can confirm that the issue is fixed. btw, building `awesome-git` did stop with errors for me.
