### ISSUE TITLE
new windows open on the wrong monitor in a triple head setup

### ISSUE THREAD

**Issue by robomancer-or** [awesomeWM/awesome#1721]
Output of `awesome --version`:

awesome v3.5.6 (For Those About To Rock)
 • Build: Sep  1 2015 11:28:53 for x86_64 by gcc version 5.2.1 (buildd@lgw01-18)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔

I'm using an up to date copy of Ubuntu and my .xprofile is:
xrandr --output DP-1 --size 1920x1200 --rate 59.95 --pos 1920x0 --rotate left
xrandr --output DP-3 --size 1920x1200 --rate 59.95 --pos 3120x260
xrandr --output DP-4 --size 1920x1080 --rate 60.02 --pos 0x840

**How to reproduce the issue:**

Use a laptop (DP-4 in my case) and two external displays.  Put the mouse focus within each screen and spawn a window.

**Actual result:**

Two of the windows spawn on the laptop screen, even though one of them was spawned with the focus in an external display.  Also observe that windows spawn correctly on the other monitor (when focus is there).  In my case it's DP-3 that won't spawn windows, although I have no trouble dragging them there.  It doesn't matter if there are already windows on the display that can't spawn.

**Expected result:**

Windows should open on whatever monitor has focus.

**Comment by Elv13** [comment]
Hello,

The current release of Awesome is 4.1. While I know 3.5.6 still ships on many distribution, it is end of lifed. The code for this feature has been rewritten since 3.5.6 was released. I am not saying the bug is fixed, as it has proven many time before that this is a complex issue. However, there is many unit and integration tests that currently exists and prove that this bug has been solved.

Please try again with v4.1.

**Comment by robomancer-or** [comment]
Tried.  Almost managed to get it to run.  After a few hours I gave up,
manually uninstalled, and switched back to 3.5.6.  It's good to know that
in a few years when 4.1 gets to the Ubuntu repos this problem will go
away...

**Comment by blueyed** [comment]
@robomancer-or 
I've found that there is some PPA, but currently provides 4.0 only: https://launchpad.net/~klaus-vormweg/+archive/ubuntu/awesome.
Maybe you want to contact the maintainer (https://launchpad.net/~klaus-vormweg).
But is waiting for 4.1 to be packaged for Debian maybe (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=858170).
I assume you have tried the `make package` already?

**Comment by idl0r** [comment]
I have 4.1. running here and it's still broken.
Mouse cursor on screen 1 and e.g. starting a terminal will start it on screen 1. The same on screen 2 works as well but doing the same on screen 3 doesn't work and probably more screens wouldn't work properly either.

**Comment by Elv13** [comment]
@idl0r This may have been fixed 3 days ago, please try the latest git build

**Comment by psychon** [comment]
> I'm using an up to date copy of Ubuntu and my .xprofile is:
> xrandr --output DP-1 --size 1920x1200 --rate 59.95 --pos 1920x0 --rotate left
> xrandr --output DP-3 --size 1920x1200 --rate 59.95 --pos 3120x260
> xrandr --output DP-4 --size 1920x1080 --rate 60.02 --pos 0x840

Oh. Nothing at position 0x0. Yup, this might very well be fixed by 1332288f9de1affaaad8d292816cdf1b17e645e7.

**Comment by Elv13** [comment]
Closing as @idl0r issue has been resolved with  1332288 and @robomancer-or one was resolved with  #1091
