### ISSUE TITLE
High memory usage with client.shape

### ISSUE THREAD

**Issue by renatofdds** [awesomeWM/awesome#2050]
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1

**How to reproduce the issue:**

Add to awesome configuration:
```lua
	client.connect_signal(
		"manage",
		function (c)
			c.shape = function(cr,w,h)
			    gears.shape.rounded_rect(cr,w,h,3)
			end
		end
	)
```

**Actual result:**

Awesome consumes about 35MB of memory with every client spawned independent from the client program, e.g. with 15 clients memory usage is 700MB.

**Expected result:**

Memory usage close to the usage without rounded borders, e.g. with 15 clients i get about 40MB.

**Comment by psychon** [comment]
Does running `awesome-client 'local a = collectgarbage("count") collectgarbage("collect") collectgarbage("collect") return a, collectgarbage("count")'` in a terminal help? What does it output?

**Comment by renatofdds** [comment]
It doesn't fix it, although it show an interesting behaviour. When i run it, the memory doesn't drop, but if i spawn new clients it doesn't go up unless i spawn more clients then i used to get to that point. 

Example:
- Start awesome: ~40MB
- Spawn 5 clients: ~400MB
- Run the command, output:
```
   double 13515.3
   double 6169.28
```
- Spawn up to 5 *more* clients: ~400MB
- Spawn 6th(11th) client: 422MB
- Spawn 7th(12th) client: 447MB

And so on...

**Comment by psychon** [comment]
Hm, okay. Sorry that I didn't do this yesterday (didn't have much time), but now I actually tested it. I opened a terminal and ran `for x in $(seq 0 40) ; do urxvt -e sleep 1 & sleep 0.2 ; done`. Awesome's peak memory usage was about 50 MiB residential according to top, so I'll claim that I cannot reproduce this.

In fact, I now remembered #1960 and thus I think this was already fixed / improved.

**Comment by psychon** [comment]
I ran `awesome` under `valgrind --tool=massif` with `DISPLAY=:5 ; for x in $(seq 0 1000) ; do urxvt -e sleep 5 & sleep 0.3 ; done` (note: not the full 1000 iterations were done; in fact I have no idea how many clients were opened). The resulting memory usage graph looks like this:
```
    MB
146.2^     #                                                                  
     |     #                                                                  
     |     #                                                                  
     |     #                                                                  
     |     #:                                                                 
     |   @ #:                                                                 
     |   @ #:                                                                 
     |   @ #:              :        :               :                  : :  @ 
     |   @ #:      :       :     :  :        : :  : : :: :        : :  : :  @ 
     |   @:#:      :    :  : :   :  : : :    : :  : : :  : : :  @ : :  : :  @:
     |  :@:#:      : :  :  : ::: :  : : : :: : :  : : :  : : :  @:: : :: : :@:
     |  :@:#:::    : :  :::: ::  :  : : : :  : :  : : : :: : : :@:: : :: : :@:
     |  :@:#:: :@  : :  :: : ::  :  : : : :  : :  ::: : :::: : :@:: : :::: :@:
     |:::@:#:: :@ :: : ::: : ::  :  ::: : : :: :  ::::: :::: : :@:::: @:::::@:
     |: :@:#:: :@ :: : ::: :::: @:::::::: : ::::::::::: ::::::::@:::: @:::::@:
     |: :@:#:: :@:::@: ::: : :: @:: ::::::: ::::: ::::: ::::::::@:::::@:::::@:
     |: :@:#:: :@:::@::::: : :: @:: ::::::: ::::: ::::: ::::::::@:::::@:::::@:
     |: :@:#:: :@:::@::::: : :: @:: ::::::: ::::: ::::: ::::::::@:::::@:::::@:
     |: :@:#:: :@:::@::::: : :: @:: ::::::: ::::: ::::: ::::::::@:::::@:::::@:
     |: :@:#:: :@:::@::::: : :: @:: ::::::: ::::: ::::: ::::::::@:::::@:::::@:
   0 +----------------------------------------------------------------------->Gi
     0                                                                   163.6
```
If you now say that 150 MiB is a bit much, I'd agree. However, I'm not quite sure where that comes from. Looking at the distribution for peak memory usage (the line marked with `#`) says that must memory is in use for pixel data with this backtrace:
```
->69.47% (106,470,428B) 0xA4C65F8: ??? (in /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.34.0)
| ->69.47% (106,470,428B) 0xA4C66AB: ??? (in /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.34.0)
|   ->69.47% (106,470,428B) 0x71EC8C5: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11400.10)
|     ->69.32% (106,235,856B) 0x72245A2: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11400.10)
|     | ->69.32% (106,235,856B) 0x71DD2C3: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11400.10)
|     |   ->69.32% (106,235,856B) 0x71D48B0: cairo_push_group_with_content (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11400.10)
|     |     ->69.32% (106,235,856B) 0x9826036: ffi_call_unix64 (in /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4)
|     |       ->69.32% (106,235,856B) 0x9825A98: ffi_call (in /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4)
|     |         ->69.32% (106,235,856B) 0xDB764E2: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.2-lgi.so.0.0.0)
|     |           ->69.32% (106,235,856B) 0x7FFBC73: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.2.so.0.0.0)
|     |             ->69.32% (106,235,856B) 0x8007823: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.2.so.0.0.0)
|     |               ->69.32% (106,235,856B) 0x7FFBF9C: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.2.so.0.0.0)
|     |                 ->69.32% (106,235,856B) 0x7FFB5CD: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.2.so.0.0.0)
|     |                   ->69.32% (106,235,856B) 0x7FFC1FF: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.2.so.0.0.0)
|     |                     ->69.32% (106,235,856B) 0x7FF809F: lua_pcallk (in /usr/lib/x86_64-linux-gnu/liblua5.2.so.0.0.0)
|     |                       ->69.32% (106,235,856B) 0x12E5E3: luaA_class_call_handler (luaclass.c:414)
|     |                         ->69.32% (106,235,856B) 0x12F8ED: luaA_class_newindex (luaclass.c:506)
|     |                           ->69.32% (106,235,856B) 0x7FFBC73: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.2.so.0.0.0)
|     |                             ->69.32% (106,235,856B) 0x7FFBFB6: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.2.so.0.0.0)
|     |                               ->69.32% (106,235,856B) 0x8006810: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.2.so.0.0.0)
|     |                                 ->69.32% (106,235,856B) 0x8008103: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.2.so.0.0.0)
|     |                                   ->69.32% (106,235,856B) 0x7FFBF9C: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.2.so.0.0.0)
|     |                                     ->69.32% (106,235,856B) 0x7FFB5CD: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.2.so.0.0.0)
|     |                                       ->69.32% (106,235,856B) 0x7FFC1FF: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.2.so.0.0.0)
|     |                                         ->69.32% (106,235,856B) 0x7FF809F: lua_pcallk (in /usr/lib/x86_64-linux-gnu/liblua5.2.so.0.0.0)
|     |                                           ->69.32% (106,235,856B) 0x130979: signal_object_emit (lualib.h:75)
|     |                                             ->69.32% (106,235,856B) 0x12F5A3: luaA_class_emit_signal (luaclass.c:321)
|     |                                               ->69.32% (106,235,856B) 0x130D0B: luaA_object_emit_signal (luaobject.c:311)
|     |                                                 ->69.32% (106,235,856B) 0x137600: client_manage (client.c:1533)
|     |                                                   ->69.32% (106,235,856B) 0x120423: event_handle (event.c:811)
```
So, Lua calls `cairo_push_group_with_content` and that causes a memory allocation in pixman. However, there is no call to `cairo_push_group_with_content` in all of awesome?! Perhaps some tail call optimisation with `cairo_push_group`?
However, the only (relevant) call to `cairo_push_group` is in awful.client.shape.get_transformed() and that code makes sure that Lua does not get a reference to the group that would be kept alive via the GC... Oh, but the cairo context still has the source!

**Comment by psychon** [comment]
With the following patch:
```diff
diff --git a/lib/awful/client/shape.lua b/lib/awful/client/shape.lua
index 636600d3e..6dcb563e4 100644
--- a/lib/awful/client/shape.lua
+++ b/lib/awful/client/shape.lua
@@ -80,6 +80,10 @@ function shape.get_transformed(c, shape_name)
         cr:pop_group_to_source()
         cr:set_operator(cairo.Operator.IN)
         cr:paint()
+
+        -- 'cr' is kept alive until Lua's GC frees it. Make sure it does not
+        -- keep the group alive since that's a large image surface.
+        cr:set_source_rgba(0, 0, 0, 0)
     end
 
     return result
```
the memory usage graph now looks like this (notice that the peak is now at just 50 MiB, 1/3rd of what it was before!; also peak memory usage is now much more evenly spread across backtraces and in fact 75% of memory was allocated inside of Lua)
```
    MB
49.29^                   #                                                    
     |                   #                                                    
     |                   #                                    : @       :     
     |                   #          ::            :    :      : @       :     
     |                   #      @   :        ::   : :: : ::   : @  :    :    :
     |           ::   ::@#::    @   :        :    : :  : :    : @  : :  :    :
     |        @@ : @  : @#:     @   : @@:::: :    : :  : :   :: @  : :  :    :
     |    ::: @  : @  : @#:     @:::: @ : :  : :: : : :: : @ :::@  : :  ::   :
     |    : : @  : @  : @#: ::  @: :: @ : :  : :  ::: :::: @ :::@::: :  :::: :
     |    : : @ :: @::: @#: : ::@: :: @ : : :: : :::: :::: @ :::@: :::@@:::  :
     |   :: ::@ :: @: : @#: : : @: :: @ : : :: : :::: :::: @::::@: :::@ :::  :
     |  ::: ::@ :: @: : @#: : : @: :: @ : : :: : :::: :::: @::::@: :::@ :::  :
     |  ::: ::@ :: @: : @#: : : @: :: @ : : :: : :::: :::: @::::@: :::@ ::: @:
     |  ::: ::@ :: @: : @#: : : @: :: @ : : :: : :::: :::: @::::@: :::@ ::: @:
     |  ::: ::@ :: @: : @#: : : @: :: @ : : :: : :::: :::: @::::@: :::@ ::: @:
     |  ::: ::@ :: @: : @#: : : @: :: @ : : :: : :::: :::: @::::@: :::@ ::: @:
     |  ::: ::@ :: @: : @#: : : @: :: @ : : :: : :::: :::: @::::@: :::@ ::: @:
     |  ::: ::@ :: @: : @#: : : @: :: @ : : :: : :::: :::: @::::@: :::@ ::: @:
     |  ::: ::@ :: @: : @#: : : @: :: @ : : :: : :::: :::: @::::@: :::@ ::: @:
     |  ::: ::@ :: @: : @#: : : @: :: @ : : :: : :::: :::: @::::@: :::@ ::: @:
   0 +----------------------------------------------------------------------->Gi
     0                                                                   160.1
```
I'll create a PR with the above patch and will assume that it fixes this issue.

**Comment by renatofdds** [comment]
I tested with awesome-git (arch) and the problem is not fixed. I'll further investigate the issue and report back here.

**Comment by psychon** [comment]
@renatofdds Did you test the patch that I posted above? Note that the three comments above represent three different "states of me". The first one being "surely this was already fixed", the second one being "hm, no, something is going on...", and the third one "here is a fix that makes things work a lot better".

**Comment by renatofdds** [comment]
@psychon I tested now with your patch, although the usage is a little higher then without using shapes (which is expected), the issue gets fixed, i get 60MB with 15 clients. 

But i noticed that without shapes awesome is much snappier manipulating windows: without shapes it's instantaneous, with shapes i can notice a little transition time, so i won't be using it anymore, but that's another issue... 

You can close this once your patch gets merged. Thank you very much!
