### ISSUE TITLE
Strange Firefox maximizing

### ISSUE THREAD

**Issue by drastus** [awesomeWM/awesome#2752]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

Run Firefox (using key shortcut or autostart from rc.lua) on a tag with floating layout.

Currently I have the following rule in rc.lua:
`    { rule = { class = "Firefox" },
      properties = { tag = "X" } },`
Also tried with this:
`    { rule = { class = "Firefox" },
      properties = { tag = "X", maximized_vertical = true, maximized_horizontal = true } },`
and this rule:
`    { rule = { class = "Firefox" },
      properties = { tag = "X", callback = function (c) c.maximized = true end } },`
but effects are the same.

**Actual result:**

Firefox is not maximized. Or – strictly speaking – it is maximized but browser content fills only part of the window, the rest is just white (or sometimes black) background, as on the [screenshot](https://imgur.com/a/RoQWejP).

I fix it by demaximizing and maximizing again (Mod4+M twice). On the next run Firefox is maximized normallly, but the next time I experience this strange behavior again. Overall, in 50% of the cases maximization works correctly, the other 50% I have to fix manually.

**Expected result:**

Firefox always runs maximized.

**Comment by psychon** [comment]
Two random ideas (and no good idea on what is going on here):

- Are you using some compositing manager? (`xcompmgr`, `compton`, ...) If so, does killing it / not running it help?
- Can you check the actual size of the Firefox window? In both variants of "broken maximisation"? To do so, run `xwininfo` in a terminal and click the Firefox window. This provides lots of information, among that `Width` and `Height`. Could you also do the same with `xwininfo -frame` and see if that provides different values?

**Comment by drastus** [comment]
Okay, I discovered that the two variants of "broken maximisation" are in fact the same: when I run Firefox on the tag that is currently visible, I see the variant with white background and maximized toolbar. But when I switch from another tag (or switch to another tag and then return), the background fills with content of that tag (it can be fragment of another program or just wallpaper); also the toolbar adjusts then to the width of the browser content, like on the first screenshot.

I don't use any compositing manager. Both `xwinfo` and `xwinfo -frame` yield the same values for `Width` and `Height`, no matter if it's broken or correct maximization. Other values are the same, too.

Here is the full output of `xwinfo` for the broken variant:
```
xwininfo: Window id: 0x1600010 "Strange Firefox maximizing · Issue #2752 · awesomeWM/awesome - Mozilla Firefox"

  Absolute upper-left X:  1
  Absolute upper-left Y:  21
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 1364
  Height: 746
  Depth: 24
  Visual: 0xcd
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x1600002 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +1+21  -1+21  -1-1  +1-1
  -geometry 1364x746+0-0
```

And `xwinfo -frame` for the broken maximization:
```
xwininfo: Window id: 0x80006c (has no name)

  Absolute upper-left X:  0
  Absolute upper-left Y:  20
  Relative upper-left X:  0
  Relative upper-left Y:  20
  Width: 1364
  Height: 746
  Depth: 32
  Visual: 0x6b
  Visual Class: TrueColor
  Border width: 1
  Class: InputOutput
  Colormap: 0x800000 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: yes
  Corners:  +0+20  -0+20  -0-0  +0-0
  -geometry 1364x746+0-0
```

**Comment by Elv13** [comment]
Some questions that should help narrow the scope of where the problem is:

* Did it work with previous versions of Awesome?
* Is the problem fixed by toggling floating mode (`ctrl+mod4+space`), remove maximization, resizing firefox and then make it tiled again? (remove the extra `awful.rules`).
* Did it stop working when upgrading Awesome or when upgrading Firefox?
* Does it work properly when a compositing manager is running?
* Does it work properly when Awesome is started with `--no-argb`?
* Is Firefox the only affected app?

I have seen this before, but I can't reproduce it on purpose. Note that I have a patched version of Awesome with some code prevent applications from requesting to be started maximized. That's probably enough to get rid of such problem, but it has many problems on its own and can't be merged (https://github.com/awesomeWM/awesome/pull/2429)

**Comment by Veratil** [comment]
The blank white window happens to me when I restart Firefox and open a previous session of windows which some were on non-visible tags.

I do use xcompmgr. I can make a few tests later without it running to see if that changes.

**Comment by drastus** [comment]
>     * Did it work with previous versions of Awesome?
>     * Did it stop working when upgrading Awesome or when upgrading Firefox?

It had started in previous version of Awesome (4.2), upgrading to 4.3 didn't help. I'm sure that upgrading Awesome to 4.2 didn't start the problem, it started later, maybe with some library upgrade.

>     * Is the problem fixed by toggling floating mode (`ctrl+mod4+space`), remove maximization, resizing firefox and then make it tiled again? (remove the extra `awful.rules`).

Only Mod4+M pressed twice helps.

>     * Does it work properly when a compositing manager is running?

I've just installed and run Compton, but it didn't help.

>     * Does it work properly when Awesome is started with `--no-argb`?

No, still the same.

>     * Is Firefox the only affected app?

Yes, other apps maximize correctly.

**Comment by alfunx** [comment]
I think this is not only related to maximizing. I can reproduce this behavior even like this:

* Open Firefox and one or a few other applications in some tiling layout

* Close Firefox

* Close (some of) the other applications

* Open Firefox again

(You may have to try this a few times, it didn't reproduce every time.)

Firefox seems to remember the size it had prior to closing it. After restarting it, it seems to use only the space it used before. As soon as Firefox is resized it uses the whole space.

<details><summary>Screenshots</summary>

![screenshot 1](https://i.imgur.com/5F3zzJj.png)

![screenshot 2](https://i.imgur.com/gYjqnAm.png)

</details>
<details><summary><tt>xwininfo</tt> on broken window</summary>

```
xwininfo: Window id: 0x1c00010 "DuckDuckGo — Privacy, simplified. - Mozilla Firefox"

  Absolute upper-left X:  32
  Absolute upper-left Y:  61
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 1856
  Height: 987
  Depth: 24
  Visual: 0x141
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x1c00002 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +32+61  -32+61  -32-32  +32-32
  -geometry 1856x987+28-28
```

</details>
<details><summary><tt>xwininfo -frame</tt> on broken window</summary>

```
xwininfo: Window id: 0xa00348 (has no name)

  Absolute upper-left X:  28
  Absolute upper-left Y:  57
  Relative upper-left X:  28
  Relative upper-left Y:  57
  Width: 1856
  Height: 987
  Depth: 32
  Visual: 0xbf
  Visual Class: TrueColor
  Border width: 4
  Class: InputOutput
  Colormap: 0xa00000 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: yes
  Corners:  +28+57  -28+57  -28-28  +28-28
  -geometry 1856x987+28-28
```

</details>
<details><summary><tt>xwininfo</tt> on fixed window</summary>

```
xwininfo: Window id: 0x1c00010 "DuckDuckGo — Privacy, simplified. - Mozilla Firefox"

  Absolute upper-left X:  32
  Absolute upper-left Y:  61
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 1856
  Height: 987
  Depth: 24
  Visual: 0x141
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x1c00002 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +32+61  -32+61  -32-32  +32-32
  -geometry 1856x987+28-28
```

</details>
<details><summary><tt>xwininfo -frame</tt> on fixed window</summary>

```
xwininfo: Window id: 0xa00348 (has no name)

  Absolute upper-left X:  28
  Absolute upper-left Y:  57
  Relative upper-left X:  28
  Relative upper-left Y:  57
  Width: 1856
  Height: 987
  Depth: 32
  Visual: 0xbf
  Visual Class: TrueColor
  Border width: 4
  Class: InputOutput
  Colormap: 0xa00000 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: yes
  Corners:  +28+57  -28+57  -28-28  +28-28
  -geometry 1856x987+28-28
```

</details>

**Comment by Veratil** [comment]
Did a few simple restart tests with Tab Session Manager. With xcompmgr off, I was able to open Firefox normally without having any drawing issues. With xcompmgr on, Firefox has drawing issues when resuming a session.

**Comment by izzymg** [comment]
Firefox attempts to restore its window size, and it looks like Awesome WM forces its width and height to 100% when in maximised mode. You can reproduce [this](https://user-images.githubusercontent.com/30461139/56546677-2979e200-65cf-11e9-81ef-3f02b2b06774.png) consistently by opening a window and navigating to say Github in a floating or tiled non-maximised Firefox window, then closing and opening Firefox, maximising it, navigating to say Wikipedia, then going to History -> Restore Previous Session. Doing the same in Openbox, for example, causes the Firefox window to simply restore its geometry as it was, un-maximised.

Un-maximising and re-maximising the window always solves the issue.

**Comment by psychon** [comment]
@izzymg Thanks for the info. As the `xwininfo` output shows, Firefox fails to restore its geometry here, even though it tries. :-)

What AwesomeWM is doing: When it gets a ConfigureRequest for a client https://github.com/awesomeWM/awesome/blob/7ff635bde004ccfc089710c540e5d729e5aae91d/event.c#L334, it collects the contents of that request and emits `request::geometry` on this client https://github.com/awesomeWM/awesome/blob/7ff635bde004ccfc089710c540e5d729e5aae91d/event.c#L417. Also, a boolean flag is set to remember that we got this request https://github.com/awesomeWM/awesome/blob/7ff635bde004ccfc089710c540e5d729e5aae91d/event.c#L391. This request ends up in `awful.ewmh` where it is basically ignored for fullscreen windows. https://github.com/awesomeWM/awesome/blob/7ff635bde004ccfc089710c540e5d729e5aae91d/lib/awful/ewmh.lua#L404-L418

At the end of the current main loop iteration, that `got_configure_notify` flag is handled via `client_geometry_refresh()` (called via `a_glib_poll()` -> `awesome_refresh()` -> `client_refresh()` -> `client_geomety_refresh()`. This function resizes clients that were resized https://github.com/awesomeWM/awesome/blob/7ff635bde004ccfc089710c540e5d729e5aae91d/objects/client.c#L1415-L1427 but it also sends a notify to clients that sent us a ConfigureRequest which was rejected (no resize happened) https://github.com/awesomeWM/awesome/blob/7ff635bde004ccfc089710c540e5d729e5aae91d/objects/client.c#L1399-L1406

So.... if we could somehow test that AwesomeWM actually sends this event in response to Firefox requesting maximisation, I'd say that everything on our side is working correctly. However, I'd be surprised if this event were not sent.

**Comment by sigprof** [comment]
Please also specify the Firefox version — looks like the problem in this case is actually in Firefox.

I tested Firefox ESR 60.6.1 with an almost clean user profile (removed `~/.mozilla` and  `~/.cache/mozilla`, then enabled the session restore option in Firefox settings). With this version the problem appears both in Awesome 4.3 and i3 4.16.1: Firefox remembers the window size which was used when exiting, and at the next startup it draws its window as if it has the same size as before, even if the new window size is different (if the new window is smaller than it was before, some parts of the window become unreachable). Probably Firefox developers who implemented the session restore feature did not think that their request to resize the window may be denied by the WM.

Next, I installed Firefox 66.0.1 on the same machine, removed `~/.mozilla` and  `~/.cache/mozilla` again and enabled the session restore option in Firefox settings. With this Firefox version I could not reproduce the problem (again tried both Awesome 4.3 and i3 4.16.1): when Firefox is started, I see that initially it attempts to draw its UI using the previously remembered window size, but a second later it redraws using the proper window size.

**Comment by mustaqimM** [comment]
I used to experience the same on KDE with kwin and now on awesome with compton. I don't think it's the DE or compositor causing this, rather it's Firefox. On Firefox Nightly it occurs on every startup. I have to press `F11` twice for it to behave correctly.
