### ISSUE TITLE
Qt5 & tray icon = fail

### ISSUE THREAD

**Issue by alxchk** [awesomeWM/awesome#283]
So, I have 
+ awesome (d51a647003908a9e052e6592a947e90342476a3c)
+ Qt 5.4.2
+ mysystray = wibox.widget.systray()

And Qt tray icons looks like shit.
Dropbox icon is with grey background, hipchat icon overwrites other icons.
![tray1](https://cloud.githubusercontent.com/assets/329535/8508831/83322bd2-2289-11e5-98d1-c2482b059b82.png)
![tray2](https://cloud.githubusercontent.com/assets/329535/8508832/8335c17a-2289-11e5-9ba9-5aac7a89ae2f.png)

**Comment by actionless** [comment]
https://github.com/awesomeWM/awesome/issues/176

**Comment by psychon** [comment]
Wow, that "hipchat overwrites other icons" is a new one. No idea how they actually manage to do that, but apparently they fight with awesome and are not happy with the size that is assigned to their tray icon.
Anyway, that's a different issue than the "Qt5 does not support transparency with tray icons" one.

**Comment by alxchk** [comment]
If it matters, vlc/qt5 case is the same as with hipchat. Also I have this in config:
bottombox = awful.wibox({ position = "bottom", screen = 1,
                          fg = '#00FF00',.
                          bg = '#000000',.
                          height = 16})

bottombox <- panel with tray

**Comment by actionless** [comment]
can't reproduce it no more: `dropbox 3.4.6`

**Comment by psychon** [comment]
The hipchat problem should be worked around with 4daa6e8befeb2461eaa298195d0296f85ce7fd4d, the background problem is on Qt's side and is hopefully fixed with Qt 5.5 or 5.6. Reopen if I am wrong.

**Comment by alxchk** [comment]
awesome v3.5.2-929-g8557a7e-dirty (The Fox)
 • Build: Nov 21 2015 19:55:20 for x86_64 by gcc version 4.9.3 (@wintermute.alxchk.me)
 • Compiled against Lua 5.2.3 (running with Lua 5.2)
 • D-Bus support: ✔

Still same behaviour with hipchat =\

The problem not just with size. Hipchat icon just put itself over existing icons.

**Comment by lknix** [comment]
awesome v3.5.8 (Major Tom)
 • Build: Feb  2 2016 00:30:55 for x86_64 by gcc version 5.3.0 (builduser@rw)
 • Compiled against Lua 5.3.2 (running with Lua 5.3)
 • D-Bus support: ✔

HipChat icon still overrides other icons. I've forced HipChat to use other icon sizes and it doesn't solve the problem. As @alxchk said HipChat just puts itself over other icons. It's very annoying - is there a way to just blacklist HipChat from systray?
