### ISSUE TITLE
No GObject signals from playerctl library when used with Awesome

### ISSUE THREAD

**Issue by regan3** [awesomeWM/awesome#3311]
Output of `awesome --version`: 
awesome v4.3-897-g66b1780d8-dirty (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no

So I am trying to use the [playerctl](https://github.com/altdesktop/playerctl) library from within my Awesome configuration using the lgi bindings. Some of the functionality does work but connecting to any of the library signals does not appear to work. Here's an example

```
local naughty = require("naughty")
local Playerctl = require("lgi").Playerctl

local manager = Playerctl.PlayerManager()

function manager:on_name_appeared(name)
    naughty.notification {
        title = "New player detected",
        message = name.name
    }
end
```
I see no notification when a MPRIS compatible application is started with this code included in my Awesome config. I have confirmed that this behavior is specific to Awesome by running the following code as an independent lua script.

```
local lgi = require("lgi")
local GLib = lgi.GLib
local Playerctl = lgi.Playerctl

local manager = Playerctl.PlayerManager()

function manager:on_name_appeared(name)
    print(string.format("New player detected: %s", name.name))
end

local main = GLib.MainLoop()
main:run()
```

With this code I do see the expected print statement when a MPRIS compatible application is started. I am not very familiar with GLib, but I know Awesome runs its own main loop at startup and there seems to be a disconnection such that the playerctl signals are not being emitted. There may be a more fundamental reason why this is not possible, but 
like I said, I'm not super familiar with GLib and thought I would ask here.

**Comment by Elv13** [comment]
I think this is caused by AwesomeWM starting before the "proper" dbus session. This can happen depending on how AwesomeWM is started. However, usually, when that happens, other stuff like Naughty notification tend to misbehave in some way. Can you try this:

```
ctrl+alt+f2
<login>
X :1 & 
sleep 10
DISPLAY=:1 dbus-launch awesome
ctrl+alt+whatever_it_is_at_usually_f8
```

And try your code? If what doesn't work, can you repeat the thing above in Xephyr (an X server that runs in a window)?

AwesomeWM uses an event loop. So it /should/ work. However, we have seen problems like that where some code just doesn't like running in a window manager. I tried implementing MPRIS using GDbus directly about 10 years ago and ran into some issues. However most of them turned out to be bugs in LGI and are fixed. To debug, you might also want to take a look at "bustle", a DBus debugger.

**Comment by regan3** [comment]
Thanks for your response. I had some issues running those commands in a tty so I just ended up running
```
Xephyr :1
DISPLAY=:1 dbus-launch awesome
```
I still didn't see any notifications when starting an MPRIS application (I tested with Spotify). I also used bustle to look at the DBus traffic, and while I am not an expert in the MPRIS interface, I didn't see anything that looked out of the ordinary. Several signals with what looked like correct info when Spotify was started. It seems like those signals are not being detected by Awesome. The DBus signals from Spotify were on the session bus. Is it possible Awesome is on the system bus and therefore not seeing those signals?

**Comment by regan3** [comment]
Ok I did a little bit more debugging tonight and tried linking my code from above to a keybind so I could run it manually after Awesome was fully started and it seems to work. I'm still not entirely sure why though.

**Comment by Elv13** [comment]
If you try to attach the code to a oneshot `gears.timer`, does it also work?

**Comment by regan3** [comment]
Yeah right after that started working I tried it on a timer with timeout 1 sec (Awesome starts up pretty quick for me) and it also worked. I tried running it as a `gears.timer.delayed_call` and that worked as well. It seems like it only works after the Awesome main event loop has been started? Or maybe there's something else related to dbus that gets initialized after the configuration code is run? Either way the `gears.timer.delayed_call` is a decent fix for now.
