### ISSUE TITLE
Can't maximize wallpaper using awful.wallpaper

### ISSUE THREAD

**Issue by PureArtistry** [awesomeWM/awesome#3547]
Output of `awesome --version`:

awesome v4.3-1336-g21b908bef (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no

**How to reproduce the issue:**

New to awesome, just setting up my config (this could be a pebkac thing, sorry for wasting your time if it is something I'm missing / doing wrong)

I'm trying to set a maximized wallpaper using awful.wallpaper and these settings:
```
screen.connect_signal('request::wallpaper', function(s)
    awful.wallpaper {
        screen = s,
        bg = FLAVOURS.base00,
        widget = {
            {
                image                 = beautiful.wallpaper,
                resize                = true,
                -- upscale               = true,
                -- downscale             = true,
                -- scaling_quality       = 'best',
                horizontal_fit_policy = "fit",
                vertical_fit_policy   = "fit",
                widget                = wibox.widget.imagebox
            },
            valign = 'center',
            halign = 'center',
            tiled  = false,
            widget = wibox.container.tile
        }
    }
end)
```
I have tried every combination of settings and values and the wallpaper is always centered with vertical borders, it appears as if some settings have no impact whatsoever.  

Using gears.wallpaper.maximized() works as expected

**Actual result:**

![scrot_20220113-012344](https://user-images.githubusercontent.com/53883649/149250517-8c3cb94b-a926-480c-97bc-f619f3c481d2.png)

**Expected result:**

![scrot_20220113-012531](https://user-images.githubusercontent.com/53883649/149250656-c8aabf00-6b5e-4538-af45-4a28a4c178ef.png)

**Comment by Elv13** [comment]
Hi, can you try (untested):

```lua
screen.connect_signal('request::wallpaper', function(s)
    awful.wallpaper {
        screen = s,
        bg = FLAVOURS.base00,
        widget = {
            image                 = beautiful.wallpaper,
            upscale               = true,
            downscale             = true,
            horizontal_fit_policy = "fit",
            vertical_fit_policy   = "fit",
            widget                = wibox.widget.imagebox
        }
    }
end)
```

**Comment by PureArtistry** [comment]
It stretches the image differently to how it looks with gears.wallpaper but that at least makes it fill the screen now, thanks.
I can fiddle with the settings again to see if I can make them match

**Comment by PureArtistry** [comment]
with awful

![scrot_20220113-021522](https://user-images.githubusercontent.com/53883649/149254515-4995b9d8-184c-46ca-9e30-2b591ef425b1.png)

![scrot_20220113-021620](https://user-images.githubusercontent.com/53883649/149254565-41d43e39-6945-4b4c-aca4-c236f65958d6.png)

with gears

![scrot_20220113-021726](https://user-images.githubusercontent.com/53883649/149254612-e89044d2-b766-4b7b-af16-e2f4c91d28f1.png)

![scrot_20220113-021738](https://user-images.githubusercontent.com/53883649/149254643-061b3523-a2d3-4c38-bd91-ed69a02b08b3.png)

I can try and find another wallpaper that makes the difference more obvious if you need me to, I know I have a couple that did the same thing (not maximize I mean)

the difference isn't huge but noticable (I'm used to my browser startpage almost perfectly lining up with the background)

**Comment by PureArtistry** [comment]
here is a clearer example

awful

![scrot_20220113-023538](https://user-images.githubusercontent.com/53883649/149256149-64950b75-0871-4b50-9d3d-ba42a2290732.png)

gears

![scrot_20220113-023612](https://user-images.githubusercontent.com/53883649/149256181-ed61d3dd-9974-441a-8c7d-2607ec4286dc.png)

**Comment by actionless** [comment]
did you tried?

```lua
            horizontal_fit_policy = "fit",
            vertical_fit_policy   = "auto",
```

**Comment by PureArtistry** [comment]
just tested it and that also doesn't maintain aspect ratio, the linked PR should fix the issue if/when it goes through

**Comment by aarav2you** [comment]
A bit unrelated but how do you access this wallpaper library? it just says attempt to call a nil value, for me only gears.wallpaper exists...

**Comment by Aire-One** [comment]
> A bit unrelated but how do you access this wallpaper library? it just says attempt to call a nil value, for me only gears.wallpaper exists...

This new library is only part of the source code on git, and is not released to the stable version of awesome. (because we haven't done a release for a while now) 

I guess you have installed awesome with your package manager and you get the stable version of awesome. So it's expected that you can't use this new library now.

**Comment by Johnystar** [comment]
This is still a problem and unfortunately (probably due to being deprecated), ``gears.wallpaper.maximized`` doesn't seem to be working anymore either.
```lua
    gears.wallpaper.maximized{
        surf = beautiful.wallpaper,
        s = s
    }  -- DEPRECATED, but the only way to easily do this that I know of
       -- https://github.com/awesomeWM/awesome/issues/3547
```
fails with
```
/usr/share/awesome/lib/gears/surface.lua:97: cairo.Surface: not directly instantiable
```

**Comment by Johnystar** [comment]
Using this as a temporary solution:
```lua
screen.connect_signal("request::wallpaper", function(s)
    awful.spawn.with_shell("nitrogen --set-zoom-fill --head=" .. s.index .. " " .. beautiful.wallpaper)
end)
```

**Comment by sclu1034** [comment]
> This is still a problem and unfortunately (probably due to being deprecated), `gears.wallpaper.maximized` doesn't seem to be working anymore either.
> 
> ```lua
>     gears.wallpaper.maximized{
>         surf = beautiful.wallpaper,
>         s = s
>     }  -- DEPRECATED, but the only way to easily do this that I know of
>        -- https://github.com/awesomeWM/awesome/issues/3547
> ```
> 
> fails with
> 
> ```
> /usr/share/awesome/lib/gears/surface.lua:97: cairo.Surface: not directly instantiable
> ```

No, "deprecated" does not mean that it breaks. You're just calling the function wrong, as expects regular arguments, not an args table:

```lua
gears.wallpaper.maximized(beautiful.wallpaper, s)
```

**Comment by Johnystar** [comment]
> > This is still a problem and unfortunately (probably due to being deprecated), `gears.wallpaper.maximized` doesn't seem to be working anymore either.
> > ```lua
> >     gears.wallpaper.maximized{
> >         surf = beautiful.wallpaper,
> >         s = s
> >     }  -- DEPRECATED, but the only way to easily do this that I know of
> >        -- https://github.com/awesomeWM/awesome/issues/3547
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > fails with
> > ```
> > /usr/share/awesome/lib/gears/surface.lua:97: cairo.Surface: not directly instantiable
> > ```
> 
> No, "deprecated" does not mean that it breaks. You're just calling the function wrong, as it expects regular arguments, not an args table:
> 
> ```lua
> gears.wallpaper.maximized(beautiful.wallpaper, s)
> ```

I'm so sorry, I'm way too used to Python so this is an easy mistake to make for me. Thank you so much, this solved my issue.

**Comment by Aire-One** [comment]
Should this issue be closed? @actionless 

The original problem relates to the new awful.wallpaper API. This is unrelated to the "temporary fix with the old gears.wallpaper" proposed in the last few posts.

**Comment by Elv13** [comment]
I think this needs to be fixed in the new API. I have half a patch in the `wibox.container.borders` branch, but it still 2 PR deep in my bucket list. I also wont have time in the next 2 weeks to work on this.

**Comment by sclu1034** [comment]
It definitely needs to be fixed in `wibox.widget.imagebox`. But if you're talking about those `pad`/`reflect`/`repeat` fit policies, I don't see how they'd help here.

We already have #3554, though, which could use some input from other people (and that doesn't have to be Elv, we've got more maintainers here).
And I think it might be better to go even further with the simplification from that PR and make a new widget type on top of `imagebox` that has only a single property with the same values that people are used to from other systems: "fit", "fill", "center", "tile", "stretch".
`imagebox` has become way too complex for this use case.

**Comment by Elv13** [comment]
I have a local patch which add the `"crop"` policy. But yeah, I haven't looked at that other patch there. It might be a better solution.

> imagebox has become way too complex for this use case.

I don't know. If we start having too many subclasses, then you can't mix the properties those subclasses have. For the `borders` widget itself, I had little choice given how incompatible it was compared to `background`. However I don't really mind internal complexity if it makes the public API simpler. That might be an unpopular opinion. Worst case scenario we could split the file into smaller ones and keep the same public module.

**Comment by alanswanson** [comment]
You haven't looked at the patch in #3554 patch at all in six months? :-(

Can I just say it's a perfect (IMHO) simplification fix and I was only waiting your confirmation before adding documentation.

**Comment by sclu1034** [comment]
> However I don't really mind internal complexity if it makes the public API simpler.

But the public API _is_ the one that's continuously gaining complexity here. We just went from "call a single function with one parameter" to "navigate through half a dozen properties on a widget, only to realize that we didn't implement what we had before".

I'm not saying that we shouldn't provide complex, low-level access at all. But merely throwing more and more things into the already complex API, until _technically_ everything the user asked for is possible, isn't going to cut it. And it's definitely not making for a "simple public API".

For a ubiquitous use case like wallpapers, we need to add some separate thing on top of `imagebox` that hides this complexity in favour of actually making that use case as simple as it used to be. The vast majority of users just wants to cover their desktop with a single picture.

#3554 heads in that direction, but also takes away functionality that can be useful in cases that aren't wallpapers. And there are still things like `upscale`+`downscale` vs `resize`.

> If we start having too many subclasses, then you can't mix the properties those subclasses have.

It's perfectly fine to have separate groups of "subclasses". Some provide generic stuff like a border or background, and those need to be flexible and are expected to be "mixed". But other, specialized ones can exist to only provide a very specific functionality.

E.g., GTK has a very generic `GtkButton` with arbitrary text, but also a `GtkLinkButton`, which is, technically, just URI verification and default styling on top of that. But because it's such a common thing, it makes sense to make it easy to use.

**Comment by alanswanson** [comment]
> #3554 heads in that direction, but also takes away functionality that can be useful in cases that aren't wallpapers. And there are still things like `upscale`+`downscale` vs `resize`.

Just a final comment - it does not take away any functionality because having separate horizontal_fit_policy and  vertical_fit_policy simply does not work.

**Comment by sclu1034** [comment]
> Just a final comment - it does not take away any functionality because having separate horizontal_fit_policy and vertical_fit_policy simply does not work.

Looking at the doc's examples, they do work exactly as designed.

**Comment by Elv13** [comment]
> E.g., GTK has a very generic GtkButton with arbitrary text, but also a GtkLinkButton, which is, technically, just URI verification and default styling on top of that. But because it's such a common thing, it makes sense to make it easy to use.

This is a valid argument, but it has 2 sides. Qt/GTK/.NET_winform design philosophy really fit your example well. They come from the peak of the OOP era (mid-90 to mid-00). This design stood the test of time. However another one existed all along. The more declarative GUI design eventually won out. You have a restricted set of tags/widget (HTML, QML_components) and a larger number of knobs (CSS/QML_properties) to tweak them. Then you embed those few tags into other tags to extend them. This is a clear case of the composition vs. inheritance design philosophies. 

AwesomeWM 3.3-3.4 and 4.x are more on the side of (pragmatic) composition. There is a smaller number of actual widgets with some containers/decorators to wrap them. These have some properties to configure the embedded container. 3.5 had a more OOP style with get/set accessor functions and all, but that's not relevant here. Normally, you can scale the complexity rather well with the composition. You can also scale it by letting more pieces be their own widgets (tasklist template, your scrollbox container with a scrollbar widget). But sometime it causes some "core" widget scope to creep a bit. I think the imagebox and background are indeed internally too complex. 

> I'm not saying that we shouldn't provide complex, low-level access at all. But merely throwing more and more things into the already complex API, until technically everything the user asked for is possible, isn't going to cut it. And it's definitely not making for a "simple public API".

I think from an API point of view, the amount of properties and knobs is still somewhat reasonable. I also don't think it is a bottomless rabbit hole. At some point I think all imagebox use cases will be covered either using properties or decorator containers. The fit policy seems a generic fix and will be useful for `wibar` use cases too. This isn't a case like the old `taglist`/`tasklist` for which people added endless random `beautiful` variables because the widget was inflexible.

For the core devs, this is definitively adding complex code. From the user point of view, that's just another knob, it doesn't add anything to the mental load or learning curve. Plus, as long as it is structured and have images, the policy has "everything in the same place" rather than being scattered across many modules.

The counter example is the background vs. borders container, where a lot of properties would have been mutually incompatible or created visual nonsense. True, the imagebox API has a "scar" left from splitting the `resize` property into 4 new properties, this is something I am ok with compared to adding another module. So there is valid, yet subjective, arguments on both sides.

> For a ubiquitous use case like wallpapers, we need to add some separate thing on top of imagebox that hides this complexity in favour of actually making that use case as simple as it used to be. The vast majority of users just wants to cover their desktop with a single picture.

That might be the way to go. I think the current `rc.lua` "example" is fine (if this issue gets fixed), but if you have strong feeling that it's convoluted and confusing, we could add a few more properties to `awful.wallpaper` to cover the most common use cases. Or even indeed subclass `place+imagebox` into `awful.widget`. This is what I ended up doing in the notification because I ran into this exact problem and the size of the boilerplate code to make it work with the core widgets was just silly. Still, I would rather fix the core of this issue where the bug is (the imagebox). Exposing a simpler API (either as a subclass or directly to the `awful.wallpaper` module would be a second step.

> You haven't looked at the patch in https://github.com/awesomeWM/awesome/pull/3554 patch at all in six months? :-(

Don't feel targeted. For the last 8 months, I didn't contribute (new+merged) code at all and only looked at issues/PR for which I was pinged/PMed many, many time for. I changed job, moved to a new city and only had mobile Internet for a while. I also had some other projects which needed my attention much more than AwesomeWM because they solved more urgent issues.

Also, it has been 15 years this year since I started to contribute to AwesomeWM, it's getting harder and harder to keep up the pace of contribution I used to have. I have generally struggled for the last 3 years to both implement all the features I want for 4.4 and also fix all the bugs marked for the milestone, let alone keeping up with all of GitHub/Reddit/StackOverflow/Discord/IRC/Emails/AFK maze of threads. I also don't want to "release early" with half finished like the wallpaper, notification and permission APIs. This issue is a clear cut example that it's not ready yet to replace the old one. v4.3 is a good release and I would rather keep it as the "stable" API than release anything buggier.

> Just a final comment - it does not take away any functionality because having separate horizontal_fit_policy and vertical_fit_policy simply does not work.

Having them combined also doesn't work. Both of them have unfixeable corner cases. Looking at it right now, the PR as it is written conflicts with another unmerged one (the `borders` one) which actually needs the horizontal/vertical magic to properly implement the CSS-like slices. However, the end-goal for your change is also valid. From what I can think of, I think the new "crop" fit policy along with making sure (and document/test) that they are compatible with `valign`/`halign` will achieve the same end-result. This preserves the flexibility while also fixing what is clearly a bug/limitation in my original implementation.
