### ISSUE TITLE
Applications Don't Redraw on Fullscreen

### ISSUE THREAD

**Issue by zstewar1** [awesomeWM/awesome#497]
Frequently when entering fullscreen in an application, either by using Mod4 + F or a fullscreen option from within the application (e.g. f11 in chrome or evince) the application will stop redrawing. The full screen becomes occupied with the last rendered state of the application, and I can exit fullscreen by repeating the fullscreen command (that is, the application does not freeze or crash, it simply does not redraw while fullscreen). After leaving fullscreen, applications resume functioning as normal.

This problem is intermittent: repeatedly switching between normal tiling and fullscreen does not always produce this bug.

Applications I tried which produced this bug:
Google Chrome
evince
gnome-system-monitor

This seems to happen mainly when chrome is on the same screen (I tried fullscreening each application 20 times and counted the number of times that it failed to redraw):

| Program | No redraw (chrome on screen) | No redraw (chrome not on screen) |
| --- | --- | --- |
| Evince | 11/20 | 1/20 |
| System Monitor | 8/20 | 0/20 |
| Chrome | 13/20 | N/A |

I'm reasonably sure that this problem is caused by Awesome. These are from doing the same thing in Cinnamon:

| Program | No redraw (chrome on screen) | No redraw (chrome not on screen) |
| --- | --- | --- |
| Evince | 0/20 | 0/20 |
| Chrome | 0/20 | N/A |

gnome-system-monitor doesn't have a builtin fullscreen, so I couldn't try it in Cinnamon.

**Comment by psychon** [comment]
Could you run awesome with the `--no-argb` argument and see if that helps?

**Comment by zstewar1** [comment]
Running with `--no-argb` does not seem to have an effect on this problem.

This is in `3.5.6`.

**Comment by hari-rangarajan** [comment]
I have this problem whenever switching to new monitors (displays) from laptop or after hibernate/suspend on the laptop display. Terminals, java applications have this problem. 

I'm also running on --no-argb

I filed a bug earlier on this: https://github.com/awesomeWM/awesome/issues/317
I would be inclined to believe there is a common redraw issue on applications that prevent them from redrawing...

**Comment by monokles** [comment]
I have the same problem on my laptop, but not on my desktop. There's not that much of a difference in the configuration of the two, however my laptop has an ATI card while my desktop has an Nvidia. Could that be related?

**Comment by barlik** [comment]
I can confirm the same problem for me. I don't think it's GPU related, as it doesn't happen under other window managers, so it's definitely a bug in awesome.

I've tried to replicate it and it happens quite randomly. When I restart awesome it fixes itself, but if I restart 2-3 more times then the problem reappears. You need to exit from full-screen to resume drawing.

Also, I've noticed strange behaviour with 'mpv' player started in full-screen, which I think is related. Sometimes mpv  do not switch to full-screen, but leaves small gap at the bottom of the screen, and also do not hide the wibox bar at the top of the screen. Pressing 'f' key two times to exit and return to full-screen resolves the issue.

**Comment by barlik** [comment]
Do you use the default config?
I've been investigating my issue with mpv player and I think the problem is caused by code handling titlebars. As, if I disable them, the issue disappears.

**Comment by psychon** [comment]
@barlik That mpv thing sounds like a different issue. Anyway: Awesome version? Do you use `--no-argb` / does that flag make a difference?

**Comment by barlik** [comment]
My awesome version:
awesome v3.5.6 (For Those About To Rock)
 • Build: May  5 2015 05:45:29 for x86_64 by gcc version 5.1.0 (builduser@)
 • Compiled against Lua 5.3.0 (running with Lua 5.3)
 • D-Bus support: ✔

@psychon
You are right, the mpv thing is not related and I'll describe the problem in another issue after some investigation.

It's strange, as I've tried to use `--no-argb` and it works and the problem disappeared for me.

**Comment by psychon** [comment]
Anything fixed by `--no-argb` is still a video driver bug, sorry.

**Comment by barlik** [comment]
Okay, thanks.

**Comment by lianxiangru** [comment]
I find this same problem with an intel's integrated driver. I remember it worked well previously. This problem seems to appear recently.

**Comment by reteo** [comment]
I am also encountering this issue.  Awesome is running with the `--no-argb` option enabled, but the issue persists; you simply see a copy of the screen just as it was the moment before fullscreening something.  

This does not seem to apply with applications that do not have a special "fullscreen" mode (text editors, terminals, etc.), but it does affect programs such as games (both native and wine), browsers (both Firefox and Chrome), and video players (vlc, mpv, and browser-based flash & HTML5 video players); anything that has its own fullscreen handler (as far as I can tell; I'm hardly a coder).

I hope this helps!

**Comment by Elv13** [comment]
> Anything fixed by --no-argb is still a video driver bug, sorry.

**Comment by blueyed** [comment]
@zstewar1 wrote:

> Running with --no-argb does not seem to have an effect on this problem.

@zstewar1 
Is this still an issue for you?
Can you try awesome master and/or the default config then, please?

**Comment by blueyed** [comment]
Same with @lianxiangru:

> --no-argb does not work for me

**Comment by boris-petrov** [comment]
This started happening for me for gVim on Awesome 4. It was working fine on 3.5.9. What should I do?

**Comment by psychon** [comment]
@boris-petrov Could your issue be #1340 / #1369 / #1388 / 5dc88da3bda3f8626d1f43b5cd1db10950c5cb76 instead of this one?

**Comment by psychon** [comment]
Yup, that's what I am saying.

**Comment by boris-petrov** [comment]
Master fixed my problem, yes. There is some annoying visual change of the small squares in the taglist widget but I guess I'll read about this in the documentation. :) Thanks a bunch!

**Comment by Elv13** [comment]
The gVim issue has it's own bug and is due to upstream (gtk2) bugs. Another fullscreen redraw issue has been fixed in v4.1. That leaves the ARGB issue, those are not Awesome bugs, so closing this again.
